name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        coverage:
          - none
        include:
          - php: '8.3'
            coverage: xdebug
    steps:
      - uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # required by Scrutinizer
      - run: composer update --no-interaction --prefer-dist
      - run: composer run test
      - if: matrix.coverage == 'xdebug'
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: '--format=php-clover test/build/coverage.xml'
